CyclomaticComplexity:
  Max: 10
MethodLength:
  Max: 40
ClassLength:
  Max: 500
ClassVars:
  Enabled: false
BlockLength:
  Enabled: false
ConditionalAssignment:
  Enabled: false
RedundantParentheses:
  Enabled: false
RedundantMatch:
  Enabled: false
PerceivedComplexity:
  Max: 15
AbcSize:
  Max: 41
